/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author bob_s
 */
public class Reportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reportes.class.getName());

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBuscarFactura7 = new javax.swing.JPanel();
        TotalReportes7 = new javax.swing.JTextField();
        NumFacturaReporte7 = new javax.swing.JTextField();
        igvReportes7 = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        BtnBuscarFactura7 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        TablaFacturaReportes7 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jlabNumFactura7 = new javax.swing.JLabel();
        jLabApellidoCliente7 = new javax.swing.JLabel();
        jLabFechaVenta7 = new javax.swing.JLabel();
        jLabNombreCliente7 = new javax.swing.JLabel();
        PanelReportes2 = new javax.swing.JPanel();
        BtStockMinimo = new javax.swing.JButton();
        BtVentasDia = new javax.swing.JButton();
        BtProductosBest = new javax.swing.JButton();
        BtVentasMes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla2Reportes = new javax.swing.JTable();
        PanelNavegacion = new javax.swing.JPanel();
        GestionProductosButton = new javax.swing.JButton();
        ClientesButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        VentasButton = new javax.swing.JButton();
        ReportesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 900));
        getContentPane().setLayout(null);

        PanelBuscarFactura7.setBackground(new java.awt.Color(255, 239, 232));

        TotalReportes7.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        TotalReportes7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        TotalReportes7.setPreferredSize(new java.awt.Dimension(74, 25));

        NumFacturaReporte7.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        NumFacturaReporte7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        NumFacturaReporte7.setMinimumSize(new java.awt.Dimension(64, 25));
        NumFacturaReporte7.setPreferredSize(new java.awt.Dimension(74, 25));
        NumFacturaReporte7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumFacturaReporteActionPerformed(evt);
            }
        });

        igvReportes7.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        igvReportes7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        igvReportes7.setPreferredSize(new java.awt.Dimension(74, 25));

        jLabel75.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel75.setText("IGV (18%):");

        jLabel76.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel76.setText("Ingresar Número de Factura");

        jLabel77.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel77.setText("Facturas");

        jLabel78.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel78.setText("TOTAL:");

        BtnBuscarFactura7.setBackground(new java.awt.Color(0, 118, 168));
        BtnBuscarFactura7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtnBuscarFactura7.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarFactura7.setText("Buscar");
        BtnBuscarFactura7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarFacturaActionPerformed(evt);
            }
        });

        TablaFacturaReportes7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(TablaFacturaReportes7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel79.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel79.setText("Fecha de Venta:");

        jLabel80.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel80.setText("Cliente");

        jLabel81.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel81.setText("Factura Nº: ");

        jLabel82.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel82.setText("Apellido:");

        jLabel83.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel83.setText("Nombre:");

        jlabNumFactura7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jlabNumFactura7.setText("_ _ _ _");

        jLabApellidoCliente7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabApellidoCliente7.setText("_ _ _ _");

        jLabFechaVenta7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabFechaVenta7.setText("_ _ _ _");

        jLabNombreCliente7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabNombreCliente7.setText("_ _ _ _");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel81)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlabNumFactura7))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel83)
                        .addGap(18, 18, 18)
                        .addComponent(jLabNombreCliente7))
                    .addComponent(jLabel80))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel79)
                        .addGap(18, 18, 18)
                        .addComponent(jLabFechaVenta7))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel82)
                        .addGap(18, 18, 18)
                        .addComponent(jLabApellidoCliente7)))
                .addGap(90, 90, 90))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabNumFactura7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabFechaVenta7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabApellidoCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabNombreCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout PanelBuscarFactura7Layout = new javax.swing.GroupLayout(PanelBuscarFactura7);
        PanelBuscarFactura7.setLayout(PanelBuscarFactura7Layout);
        PanelBuscarFactura7Layout.setHorizontalGroup(
            PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(BtnBuscarFactura7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel75)
                                    .addComponent(jLabel78))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalReportes7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(igvReportes7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                                    .addComponent(jLabel76)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(NumFacturaReporte7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel77)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PanelBuscarFactura7Layout.setVerticalGroup(
            PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumFacturaReporte7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnBuscarFactura7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(igvReportes7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalReportes7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        getContentPane().add(PanelBuscarFactura7);
        PanelBuscarFactura7.setBounds(340, 0, 520, 900);

        PanelReportes2.setBackground(new java.awt.Color(255, 239, 232));

        BtStockMinimo.setBackground(new java.awt.Color(204, 0, 0));
        BtStockMinimo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtStockMinimo.setForeground(new java.awt.Color(255, 255, 255));
        BtStockMinimo.setText("Productos por Agotarse");
        BtStockMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtStockMinimoActionPerformed(evt);
            }
        });

        BtVentasDia.setBackground(new java.awt.Color(0, 118, 168));
        BtVentasDia.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtVentasDia.setForeground(new java.awt.Color(255, 255, 255));
        BtVentasDia.setText("Ventas del Dia");
        BtVentasDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVentasDiaActionPerformed(evt);
            }
        });

        BtProductosBest.setBackground(new java.awt.Color(102, 153, 0));
        BtProductosBest.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtProductosBest.setForeground(new java.awt.Color(255, 255, 255));
        BtProductosBest.setText("Productos mas Vendidos");
        BtProductosBest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtProductosBestActionPerformed(evt);
            }
        });

        BtVentasMes.setBackground(new java.awt.Color(0, 118, 168));
        BtVentasMes.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtVentasMes.setForeground(new java.awt.Color(255, 255, 255));
        BtVentasMes.setText("Ventas del Mes");
        BtVentasMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVentasMesActionPerformed(evt);
            }
        });

        Tabla2Reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tabla2Reportes);

        javax.swing.GroupLayout PanelReportes2Layout = new javax.swing.GroupLayout(PanelReportes2);
        PanelReportes2.setLayout(PanelReportes2Layout);
        PanelReportes2Layout.setHorizontalGroup(
            PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelReportes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(21, 21, 21))
            .addGroup(PanelReportes2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtVentasDia, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelReportes2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(BtProductosBest)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(PanelReportes2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(BtVentasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelReportes2Layout.setVerticalGroup(
            PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReportes2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtVentasDia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtVentasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtProductosBest, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        getContentPane().add(PanelReportes2);
        PanelReportes2.setBounds(860, 0, 580, 900);

        PanelNavegacion.setBackground(new java.awt.Color(0, 118, 168));
        PanelNavegacion.setPreferredSize(new java.awt.Dimension(339, 900));

        GestionProductosButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        GestionProductosButton.setForeground(new java.awt.Color(255, 255, 255));
        GestionProductosButton.setText("Gestion de Productos");
        GestionProductosButton.setBorder(null);
        GestionProductosButton.setBorderPainted(false);
        GestionProductosButton.setContentAreaFilled(false);
        GestionProductosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GestionProductosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionProductosButtonActionPerformed(evt);
            }
        });

        ClientesButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        ClientesButton.setForeground(new java.awt.Color(255, 255, 255));
        ClientesButton.setText("Clientes");
        ClientesButton.setBorder(null);
        ClientesButton.setBorderPainted(false);
        ClientesButton.setContentAreaFilled(false);
        ClientesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesButtonActionPerformed(evt);
            }
        });

        SalirButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        SalirButton.setForeground(new java.awt.Color(255, 255, 255));
        SalirButton.setText("Salir");
        SalirButton.setBorder(null);
        SalirButton.setBorderPainted(false);
        SalirButton.setContentAreaFilled(false);
        SalirButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        VentasButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        VentasButton.setForeground(new java.awt.Color(255, 255, 255));
        VentasButton.setText("Ventas");
        VentasButton.setBorder(null);
        VentasButton.setBorderPainted(false);
        VentasButton.setContentAreaFilled(false);
        VentasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasButtonActionPerformed(evt);
            }
        });

        ReportesButton.setBackground(new java.awt.Color(0, 67, 96));
        ReportesButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        ReportesButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportesButton.setText("Reportes                        ");
        ReportesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ReportesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReportesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNavegacionLayout = new javax.swing.GroupLayout(PanelNavegacion);
        PanelNavegacion.setLayout(PanelNavegacionLayout);
        PanelNavegacionLayout.setHorizontalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGroup(PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNavegacionLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GestionProductosButton)
                            .addComponent(VentasButton)
                            .addComponent(ClientesButton)
                            .addComponent(SalirButton)))
                    .addGroup(PanelNavegacionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ReportesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNavegacionLayout.setVerticalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(GestionProductosButton)
                .addGap(49, 49, 49)
                .addComponent(VentasButton)
                .addGap(40, 40, 40)
                .addComponent(ReportesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(ClientesButton)
                .addGap(117, 117, 117)
                .addComponent(SalirButton))
        );

        getContentPane().add(PanelNavegacion);
        PanelNavegacion.setBounds(0, 0, 340, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionProductosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionProductosButtonActionPerformed
        GestionProductos gp = new GestionProductos();  // Crear instancia del formulario
        gp.setVisible(true);                           // Mostrar el formulario
        this.dispose();                                // Cerrar el formulario actual
    }//GEN-LAST:event_GestionProductosButtonActionPerformed

    private void ClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesButtonActionPerformed
        Clientes clientes = new Clientes();  // Crear instancia del formulario
        clientes.setVisible(true);                           // Mostrar el formulario
        this.dispose();                                // Cerrar el formulario actual
    }//GEN-LAST:event_ClientesButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        Login login = new Login();this.dispose();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void VentasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasButtonActionPerformed
        Ventas ventas= new Ventas();
        ventas.setVisible(true);
        this.dispose();    }//GEN-LAST:event_VentasButtonActionPerformed

    private void ReportesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportesButtonActionPerformed

    private void BtVentasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVentasMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtVentasMesActionPerformed

    private void BtProductosBestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtProductosBestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtProductosBestActionPerformed

    private void BtVentasDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVentasDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtVentasDiaActionPerformed

    private void BtStockMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtStockMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtStockMinimoActionPerformed

    private void BtnBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarFacturaActionPerformed

    private void NumFacturaReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumFacturaReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumFacturaReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtProductosBest;
    private javax.swing.JButton BtStockMinimo;
    private javax.swing.JButton BtVentasDia;
    private javax.swing.JButton BtVentasMes;
    private javax.swing.JButton BtnBuscarFactura7;
    private javax.swing.JButton ClientesButton;
    private javax.swing.JButton GestionProductosButton;
    private javax.swing.JTextField NumFacturaReporte7;
    private javax.swing.JPanel PanelBuscarFactura7;
    private javax.swing.JPanel PanelNavegacion;
    private javax.swing.JPanel PanelReportes2;
    private javax.swing.JButton ReportesButton;
    private javax.swing.JButton SalirButton;
    private javax.swing.JTable Tabla2Reportes;
    private javax.swing.JTable TablaFacturaReportes7;
    private javax.swing.JTextField TotalReportes7;
    private javax.swing.JButton VentasButton;
    private javax.swing.JTextField igvReportes7;
    private javax.swing.JLabel jLabApellidoCliente7;
    private javax.swing.JLabel jLabFechaVenta7;
    private javax.swing.JLabel jLabNombreCliente7;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel jlabNumFactura7;
    // End of variables declaration//GEN-END:variables
}
