/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author bob_s
 */
public class Reportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reportes.class.getName());

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNavegacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GestionProductosButton = new javax.swing.JButton();
        ReportesButton = new javax.swing.JButton();
        ClientesButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        VentasButton = new javax.swing.JButton();
        PanelProductosCRUD = new javax.swing.JPanel();
        PrecioProductoGestion = new javax.swing.JTextField();
        CodProductoGestion = new javax.swing.JTextField();
        DescripcionProductoGestion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BtnSubirImagen = new javax.swing.JButton();
        PanImageGestion = new javax.swing.JPanel();
        ActualizarProductoGestion = new javax.swing.JButton();
        GuardarProductoGestion = new javax.swing.JButton();
        EliminarProductoGestion = new javax.swing.JButton();
        BuscarProductoGestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1445, 930));
        getContentPane().setLayout(null);

        PanelNavegacion.setBackground(new java.awt.Color(0, 118, 168));
        PanelNavegacion.setPreferredSize(new java.awt.Dimension(339, 900));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Logo secciones.png"))); // NOI18N

        GestionProductosButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        GestionProductosButton.setForeground(new java.awt.Color(255, 255, 255));
        GestionProductosButton.setText("Gestion de Productos");
        GestionProductosButton.setBorder(null);
        GestionProductosButton.setBorderPainted(false);
        GestionProductosButton.setContentAreaFilled(false);
        GestionProductosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionProductosButtonActionPerformed(evt);
            }
        });

        ReportesButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        ReportesButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportesButton.setText("Reportes");
        ReportesButton.setBorder(null);
        ReportesButton.setBorderPainted(false);
        ReportesButton.setContentAreaFilled(false);
        ReportesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesButtonActionPerformed(evt);
            }
        });

        ClientesButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        ClientesButton.setForeground(new java.awt.Color(255, 255, 255));
        ClientesButton.setText("Clientes");
        ClientesButton.setBorder(null);
        ClientesButton.setBorderPainted(false);
        ClientesButton.setContentAreaFilled(false);
        ClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesButtonActionPerformed(evt);
            }
        });

        SalirButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        SalirButton.setForeground(new java.awt.Color(255, 255, 255));
        SalirButton.setText("Salir");
        SalirButton.setBorder(null);
        SalirButton.setBorderPainted(false);
        SalirButton.setContentAreaFilled(false);
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        VentasButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        VentasButton.setForeground(new java.awt.Color(255, 255, 255));
        VentasButton.setText("Ventas");
        VentasButton.setBorder(null);
        VentasButton.setBorderPainted(false);
        VentasButton.setContentAreaFilled(false);
        VentasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNavegacionLayout = new javax.swing.GroupLayout(PanelNavegacion);
        PanelNavegacion.setLayout(PanelNavegacionLayout);
        PanelNavegacionLayout.setHorizontalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1))
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(GestionProductosButton))
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(VentasButton))
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(ReportesButton))
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(ClientesButton))
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(SalirButton))
        );
        PanelNavegacionLayout.setVerticalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(GestionProductosButton)
                .addGap(49, 49, 49)
                .addComponent(VentasButton)
                .addGap(47, 47, 47)
                .addComponent(ReportesButton)
                .addGap(47, 47, 47)
                .addComponent(ClientesButton)
                .addGap(117, 117, 117)
                .addComponent(SalirButton))
        );

        getContentPane().add(PanelNavegacion);
        PanelNavegacion.setBounds(0, 0, 340, 900);

        PanelProductosCRUD.setBackground(new java.awt.Color(255, 239, 232));

        PrecioProductoGestion.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        PrecioProductoGestion.setForeground(new java.awt.Color(0, 0, 0));
        PrecioProductoGestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        PrecioProductoGestion.setPreferredSize(new java.awt.Dimension(74, 25));

        CodProductoGestion.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        CodProductoGestion.setForeground(new java.awt.Color(0, 0, 0));
        CodProductoGestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        CodProductoGestion.setMinimumSize(new java.awt.Dimension(64, 25));
        CodProductoGestion.setPreferredSize(new java.awt.Dimension(74, 25));
        CodProductoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodProductoGestionActionPerformed(evt);
            }
        });

        DescripcionProductoGestion.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        DescripcionProductoGestion.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionProductoGestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        DescripcionProductoGestion.setPreferredSize(new java.awt.Dimension(74, 25));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Descripción:");

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("CodProducto:");

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Facturas");

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Precio:");

        BtnSubirImagen.setBackground(new java.awt.Color(0, 118, 168));
        BtnSubirImagen.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtnSubirImagen.setForeground(new java.awt.Color(255, 255, 255));
        BtnSubirImagen.setText("Subir Imagen");
        BtnSubirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubirImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelProductosCRUDLayout = new javax.swing.GroupLayout(PanelProductosCRUD);
        PanelProductosCRUD.setLayout(PanelProductosCRUDLayout);
        PanelProductosCRUDLayout.setHorizontalGroup(
            PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DescripcionProductoGestion, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(CodProductoGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PrecioProductoGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSubirImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelProductosCRUDLayout.setVerticalGroup(
            PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                        .addComponent(CodProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescripcionProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(PrecioProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(168, 168, 168)
                .addComponent(BtnSubirImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(512, Short.MAX_VALUE))
        );

        getContentPane().add(PanelProductosCRUD);
        PanelProductosCRUD.setBounds(340, 0, 520, 900);

        PanImageGestion.setBackground(new java.awt.Color(255, 239, 232));

        ActualizarProductoGestion.setBackground(new java.awt.Color(210, 143, 0));
        ActualizarProductoGestion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        ActualizarProductoGestion.setForeground(new java.awt.Color(255, 255, 255));
        ActualizarProductoGestion.setText("Actualizar");
        ActualizarProductoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProductoGestionActionPerformed(evt);
            }
        });

        GuardarProductoGestion.setBackground(new java.awt.Color(0, 153, 0));
        GuardarProductoGestion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        GuardarProductoGestion.setForeground(new java.awt.Color(255, 255, 255));
        GuardarProductoGestion.setText("Guardar");
        GuardarProductoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarProductoGestionActionPerformed(evt);
            }
        });

        EliminarProductoGestion.setBackground(new java.awt.Color(204, 0, 0));
        EliminarProductoGestion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        EliminarProductoGestion.setForeground(new java.awt.Color(255, 255, 255));
        EliminarProductoGestion.setText("Eliminar");
        EliminarProductoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoGestionActionPerformed(evt);
            }
        });

        BuscarProductoGestion.setBackground(new java.awt.Color(0, 118, 168));
        BuscarProductoGestion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BuscarProductoGestion.setForeground(new java.awt.Color(255, 255, 255));
        BuscarProductoGestion.setText("Buscar");
        BuscarProductoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProductoGestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanImageGestionLayout = new javax.swing.GroupLayout(PanImageGestion);
        PanImageGestion.setLayout(PanImageGestionLayout);
        PanImageGestionLayout.setHorizontalGroup(
            PanImageGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanImageGestionLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(PanImageGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GuardarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ActualizarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        PanImageGestionLayout.setVerticalGroup(
            PanImageGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanImageGestionLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(GuardarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(BuscarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(ActualizarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(EliminarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(607, Short.MAX_VALUE))
        );

        getContentPane().add(PanImageGestion);
        PanImageGestion.setBounds(860, 0, 580, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionProductosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionProductosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GestionProductosButtonActionPerformed

    private void ReportesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportesButtonActionPerformed

    private void ClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void VentasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentasButtonActionPerformed

    private void CodProductoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodProductoGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodProductoGestionActionPerformed

    private void BuscarProductoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProductoGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarProductoGestionActionPerformed

    private void ActualizarProductoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProductoGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarProductoGestionActionPerformed

    private void GuardarProductoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarProductoGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarProductoGestionActionPerformed

    private void EliminarProductoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarProductoGestionActionPerformed

    private void BtnSubirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubirImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSubirImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarProductoGestion;
    private javax.swing.JButton BtnSubirImagen;
    private javax.swing.JButton BuscarProductoGestion;
    private javax.swing.JButton ClientesButton;
    private javax.swing.JTextField CodProductoGestion;
    private javax.swing.JTextField DescripcionProductoGestion;
    private javax.swing.JButton EliminarProductoGestion;
    private javax.swing.JButton GestionProductosButton;
    private javax.swing.JButton GuardarProductoGestion;
    private javax.swing.JPanel PanImageGestion;
    private javax.swing.JPanel PanelNavegacion;
    private javax.swing.JPanel PanelProductosCRUD;
    private javax.swing.JTextField PrecioProductoGestion;
    private javax.swing.JButton ReportesButton;
    private javax.swing.JButton SalirButton;
    private javax.swing.JButton VentasButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    // End of variables declaration//GEN-END:variables
}
