/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecsup.proyectofinal.view;

import com.tecsup.proyectofinal.model.dao.ReporteDAO;
import com.tecsup.proyectofinal.model.dao.daoimpl.ReporteDAOImpl;
import com.tecsup.proyectofinal.model.dto.ProductoVendidoDTO;
import com.tecsup.proyectofinal.model.dto.UsuarioDTO;
import com.tecsup.proyectofinal.model.dto.VentaRecienteDTO;
import com.tecsup.proyectofinal.util.DAOException;
import com.tecsup.proyectofinal.util.SesionActual;
import java.text.NumberFormat;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 51931
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    
    private final ReporteDAO reporteDAO = new ReporteDAOImpl();
    

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null); // centra la ventana en la pantalla
        
        mostrarBienvenida();
        
        cargarTotalProductosStock();
        
        cargarRepuestosCriticos();
        
        cargarVentasDia();
        
        cargarIngresosMes();
        
        cargarActividadReciente();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNavegacion = new javax.swing.JPanel();
        GestionProductosButton = new javax.swing.JButton();
        ClientesButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        VentasButton = new javax.swing.JButton();
        ReportesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LogoButton = new javax.swing.JButton();
        bgDashboard = new javax.swing.JPanel();
        bienvenidoUser = new javax.swing.JLabel();
        jpanelStock = new javax.swing.JPanel();
        lblTotalRepuestos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpanelStockCritico = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblRepuestosCriticos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jpanelVentasDia = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblVentasDia = new javax.swing.JTextField();
        jpanelIngresoMes = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblIngresosMes = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActividadReciente = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnVerRepuestosCriticos = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelNavegacion.setBackground(new java.awt.Color(0, 118, 168));
        PanelNavegacion.setPreferredSize(new java.awt.Dimension(339, 900));

        GestionProductosButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        GestionProductosButton.setForeground(new java.awt.Color(255, 255, 255));
        GestionProductosButton.setText("Gestion de Productos");
        GestionProductosButton.setBorder(null);
        GestionProductosButton.setBorderPainted(false);
        GestionProductosButton.setContentAreaFilled(false);
        GestionProductosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GestionProductosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionProductosButtonActionPerformed(evt);
            }
        });

        ClientesButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        ClientesButton.setForeground(new java.awt.Color(255, 255, 255));
        ClientesButton.setText("Clientes");
        ClientesButton.setBorder(null);
        ClientesButton.setBorderPainted(false);
        ClientesButton.setContentAreaFilled(false);
        ClientesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesButtonActionPerformed(evt);
            }
        });

        SalirButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        SalirButton.setForeground(new java.awt.Color(255, 255, 255));
        SalirButton.setText("Salir");
        SalirButton.setBorder(null);
        SalirButton.setBorderPainted(false);
        SalirButton.setContentAreaFilled(false);
        SalirButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        VentasButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        VentasButton.setForeground(new java.awt.Color(255, 255, 255));
        VentasButton.setText("Ventas");
        VentasButton.setBorder(null);
        VentasButton.setBorderPainted(false);
        VentasButton.setContentAreaFilled(false);
        VentasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasButtonActionPerformed(evt);
            }
        });

        ReportesButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        ReportesButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportesButton.setText("Reportes");
        ReportesButton.setBorder(null);
        ReportesButton.setBorderPainted(false);
        ReportesButton.setContentAreaFilled(false);
        ReportesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReportesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesButtonActionPerformed(evt);
            }
        });

        LogoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoSecciones.png"))); // NOI18N
        LogoButton.setBorder(null);
        LogoButton.setBorderPainted(false);
        LogoButton.setContentAreaFilled(false);
        LogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNavegacionLayout = new javax.swing.GroupLayout(PanelNavegacion);
        PanelNavegacion.setLayout(PanelNavegacionLayout);
        PanelNavegacionLayout.setHorizontalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGroup(PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNavegacionLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClientesButton)
                            .addComponent(SalirButton)
                            .addComponent(GestionProductosButton)
                            .addComponent(VentasButton)
                            .addComponent(ReportesButton)))
                    .addGroup(PanelNavegacionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(LogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNavegacionLayout.setVerticalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGroup(PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNavegacionLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelNavegacionLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(LogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addComponent(GestionProductosButton)
                .addGap(47, 47, 47)
                .addComponent(VentasButton)
                .addGap(47, 47, 47)
                .addComponent(ReportesButton)
                .addGap(47, 47, 47)
                .addComponent(ClientesButton)
                .addGap(117, 117, 117)
                .addComponent(SalirButton)
                .addContainerGap())
        );

        getContentPane().add(PanelNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        bgDashboard.setBackground(new java.awt.Color(255, 239, 232));
        bgDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenidoUser.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        bienvenidoUser.setText("Bienvenido, ADMIN");
        bgDashboard.add(bienvenidoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, 61));

        jpanelStock.setBackground(new java.awt.Color(255, 255, 255));
        jpanelStock.setPreferredSize(new java.awt.Dimension(234, 209));
        jpanelStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalRepuestos.setFont(new java.awt.Font("Roboto SemiBold", 0, 44)); // NOI18N
        lblTotalRepuestos.setText("70");
        lblTotalRepuestos.setBorder(null);
        lblTotalRepuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTotalRepuestosActionPerformed(evt);
            }
        });
        jpanelStock.add(lblTotalRepuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 60, 70));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Total de repuestos");
        jpanelStock.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 40));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setText("  en stock");
        jpanelStock.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon5.png"))); // NOI18N
        jpanelStock.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 50, 50));

        bgDashboard.add(jpanelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jpanelStockCritico.setBackground(new java.awt.Color(255, 255, 255));
        jpanelStockCritico.setPreferredSize(new java.awt.Dimension(234, 209));
        jpanelStockCritico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel7.setText("Repuestos con ");
        jpanelStockCritico.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel8.setText("stock critico");
        jpanelStockCritico.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lblRepuestosCriticos.setFont(new java.awt.Font("Roboto SemiBold", 0, 44)); // NOI18N
        lblRepuestosCriticos.setText("5");
        lblRepuestosCriticos.setBorder(null);
        jpanelStockCritico.add(lblRepuestosCriticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon6.png"))); // NOI18N
        jpanelStockCritico.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, 60));

        bgDashboard.add(jpanelStockCritico, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jpanelVentasDia.setBackground(new java.awt.Color(255, 255, 255));
        jpanelVentasDia.setPreferredSize(new java.awt.Dimension(234, 209));
        jpanelVentasDia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel9.setText("Ventas del dia");
        jpanelVentasDia.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 170, 40));

        lblVentasDia.setFont(new java.awt.Font("Roboto SemiBold", 0, 44)); // NOI18N
        lblVentasDia.setText("S/. 2,300");
        lblVentasDia.setBorder(null);
        jpanelVentasDia.add(lblVentasDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, 80));

        bgDashboard.add(jpanelVentasDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        jpanelIngresoMes.setBackground(new java.awt.Color(255, 255, 255));
        jpanelIngresoMes.setPreferredSize(new java.awt.Dimension(234, 209));
        jpanelIngresoMes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel10.setText("Ingresos del mes");
        jpanelIngresoMes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 190, 40));

        lblIngresosMes.setFont(new java.awt.Font("Roboto SemiBold", 0, 44)); // NOI18N
        lblIngresosMes.setText("S/. 43,250");
        lblIngresosMes.setBorder(null);
        lblIngresosMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblIngresosMesActionPerformed(evt);
            }
        });
        jpanelIngresoMes.add(lblIngresosMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 210, 80));

        bgDashboard.add(jpanelIngresoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(589, 285));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jLabel1.setText("Actividad reciente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 26, 250, 40));

        tblActividadReciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Cliente", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblActividadReciente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 75, 565, 320));

        bgDashboard.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 610, 410));

        jButton1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon4.png"))); // NOI18N
        jButton1.setText("      Exportar Reporte Diario");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bgDashboard.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 740, 370, 50));

        btnVerRepuestosCriticos.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnVerRepuestosCriticos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon1.png"))); // NOI18N
        btnVerRepuestosCriticos.setText("      Ver Repuestos Criticos");
        btnVerRepuestosCriticos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVerRepuestosCriticos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVerRepuestosCriticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRepuestosCriticosActionPerformed(evt);
            }
        });
        bgDashboard.add(btnVerRepuestosCriticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 370, 60));

        jButton5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon3.png"))); // NOI18N
        jButton5.setText("       backup base de datos");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        bgDashboard.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 630, 370, 50));

        jButton6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2.png"))); // NOI18N
        jButton6.setText("     Hay productos sin precio");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        bgDashboard.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 370, 50));

        getContentPane().add(bgDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 1100, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerRepuestosCriticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRepuestosCriticosActionPerformed
        // TODO add your handling code here:
        final int LIMITE = 5; // número de repuestos a mostrar
        ReporteDAO reporteDAO1 = new ReporteDAOImpl();
        
        try {
            var opt = reporteDAO1.obtenerProductosConMenorStock(LIMITE);

            if (opt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay repuestos críticos.", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Crear tabla con los datos
            String[] columnas = {"Código", "Descripción", "Stock Actual"};
            DefaultTableModel model = new DefaultTableModel(columnas, 0);

            for (ProductoVendidoDTO p : opt.get()) {
                model.addRow(new Object[]{
                    p.codigoProducto(),
                    p.descripcionProducto(),
                    p.stockActual()
                });
            }

            JTable tabla = new JTable(model);
            JScrollPane scroll = new JScrollPane(tabla);

            // Crear un cuadro de diálogo modal para mostrar la tabla
            JDialog dialog = new JDialog(this, "Repuestos Críticos", true);
            dialog.add(scroll);
            dialog.setSize(500, 300);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

        } catch (DAOException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener repuestos críticos:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerRepuestosCriticosActionPerformed

    private void lblIngresosMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblIngresosMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIngresosMesActionPerformed

    private void lblTotalRepuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTotalRepuestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotalRepuestosActionPerformed

    private void ReportesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesButtonActionPerformed
        Reportes reportes = new Reportes();  // Crear instancia del formulario
        reportes.setVisible(true);                           // Mostrar el formulario
        this.dispose();                                // Cerrar el formulario actual
    }//GEN-LAST:event_ReportesButtonActionPerformed

    private void VentasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasButtonActionPerformed
        Ventas ventas= new Ventas();
        ventas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VentasButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        Login login = new Login();this.dispose();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void ClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesButtonActionPerformed
        Clientes clientes = new Clientes();  // Crear instancia del formulario
        clientes.setVisible(true);                           // Mostrar el formulario
        this.dispose();                                // Cerrar el formulario actual
    }//GEN-LAST:event_ClientesButtonActionPerformed

    private void GestionProductosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionProductosButtonActionPerformed
        GestionProductos gp = new GestionProductos();  // Crear instancia del formulario
        gp.setVisible(true);                           // Mostrar el formulario
        this.dispose();                                // Cerrar el formulario actual
    }//GEN-LAST:event_GestionProductosButtonActionPerformed

    private void LogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoButtonActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_LogoButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
        this,
        "Existen productos que no tienen precio asignado.\n" +
        "Revise la gestión de productos para actualizarlos.",
        "Productos sin precio",
        JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
        this,
        "Recuerde realizar un backup regularmente.\n" +
        "Esto asegura que la información esté protegida ante fallos o pérdidas.",
        "Backup de base de datos",
        JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
        this,
        "El reporte diario contiene las ventas registradas durante el día.\n" +
        "Puede exportarlo en formatos como Excel o PDF para su análisis.",
        "Exportar Reporte Diario",
        JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClientesButton;
    private javax.swing.JButton GestionProductosButton;
    private javax.swing.JButton LogoButton;
    private javax.swing.JPanel PanelNavegacion;
    private javax.swing.JButton ReportesButton;
    private javax.swing.JButton SalirButton;
    private javax.swing.JButton VentasButton;
    private javax.swing.JPanel bgDashboard;
    private javax.swing.JLabel bienvenidoUser;
    private javax.swing.JButton btnVerRepuestosCriticos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanelIngresoMes;
    private javax.swing.JPanel jpanelStock;
    private javax.swing.JPanel jpanelStockCritico;
    private javax.swing.JPanel jpanelVentasDia;
    private javax.swing.JTextField lblIngresosMes;
    private javax.swing.JTextField lblRepuestosCriticos;
    private javax.swing.JTextField lblTotalRepuestos;
    private javax.swing.JTextField lblVentasDia;
    private javax.swing.JTable tblActividadReciente;
    // End of variables declaration//GEN-END:variables

    private void mostrarBienvenida() {
        UsuarioDTO usuario = SesionActual.getUsuarioActual();
        if (usuario != null) {
            bienvenidoUser.setText("Bienvenido, " + usuario.nombreUsuario());
        }
    }

    private void cargarTotalProductosStock() {
        try {
            long total = reporteDAO.contarTotalProductosStock();
            lblTotalRepuestos.setText(String.valueOf(total)); 
        } catch (DAOException e) {
            lblTotalRepuestos.setText("—");
        }
    }

    private void cargarRepuestosCriticos() {
        final int UMBRAL = 5; 
        try {
            long criticos = reporteDAO.contarProductosBajoStock(UMBRAL);
            lblRepuestosCriticos.setText(String.valueOf(criticos)); 
        } catch (DAOException e) {
            lblRepuestosCriticos.setText("—");
        }
    }

    private void cargarVentasDia() {
        try {
            double total = reporteDAO.calcularTotalVentasHoy();
            // Formatear a S/. con separador de miles
            lblVentasDia.setText(String.format("S/. %,.2f", total));
        } catch (DAOException e) {
            lblVentasDia.setText("S/. —");
        }
    }

    private void cargarIngresosMes() {
        try {
            double total = reporteDAO.calcularTotalVentasMesActual();
            lblIngresosMes.setText(String.format("S/. %,.2f", total));
        } catch (DAOException e) {
            lblIngresosMes.setText("S/. —");
        }
    }

    private void cargarActividadReciente() {
        final int LIMITE = 10; // cuántas filas quieres mostrar
        try {
            var opt = reporteDAO.obtenerUltimasVentas(LIMITE);
            DefaultTableModel model = (DefaultTableModel) tblActividadReciente.getModel();
            model.setRowCount(0); // limpia

            if (opt.isEmpty()) return;

            List<VentaRecienteDTO> ventas = opt.get();

            DateTimeFormatter df = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            NumberFormat moneda = NumberFormat.getCurrencyInstance(new Locale("es", "PE"));

            for (VentaRecienteDTO v : ventas) {
                model.addRow(new Object[]{
                        v.fechaEmision().format(df),
                        v.clienteNombreCompleto(),
                        moneda.format(v.total())
                });
            }

        } catch (DAOException e) {
            // opcional: mensaje o log
        }
    }
}
