/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecsup.proyectofinal.view;
import com.tecsup.proyectofinal.model.dao.daoimpl.ProductoDAOImpl;
import com.tecsup.proyectofinal.model.dto.ProductoDTO;
import com.tecsup.proyectofinal.util.SesionActual;

import java.math.BigDecimal;
import java.util.Optional;
import com.tecsup.proyectofinal.model.dao.ProductoDAO;
import com.tecsup.proyectofinal.util.DAOException;
/**
 *
 * @author bob_s
 */
public class GestionProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionProductos.class.getName());
                                        
    /**
     * Creates new form GestionProductos
     */
    public GestionProductos() {
        initComponents();
        setLocationRelativeTo(null); // centra la ventana en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNavegacion = new javax.swing.JPanel();
        ReportesButton = new javax.swing.JButton();
        ClientesButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        VentasButton = new javax.swing.JButton();
        GestionProductosButton = new javax.swing.JButton();
        LogoButton = new javax.swing.JButton();
        PanelProductosCRUD = new javax.swing.JPanel();
        PrecioProductoGestion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        FechaCreadoGestion = new javax.swing.JTextField();
        CodProductoGestion = new javax.swing.JTextField();
        StockProductoGestion = new javax.swing.JTextField();
        DescripcionProductoGestion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        BuscarProductoGestion = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        FechaModificadoGestion = new javax.swing.JTextField();
        BuscadorTextGestion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ActualizarProductoGestion = new javax.swing.JButton();
        GuardarProductoGestion = new javax.swing.JButton();
        EliminarProductoGestion = new javax.swing.JButton();
        PanImageGestion = new javax.swing.JPanel();
        ImagenProducto = new javax.swing.JLabel();
        BtnSubirImagen = new javax.swing.JButton();
        PanelProductos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaProductosGestion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 900));
        getContentPane().setLayout(null);

        PanelNavegacion.setBackground(new java.awt.Color(0, 118, 168));
        PanelNavegacion.setPreferredSize(new java.awt.Dimension(339, 900));

        ReportesButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        ReportesButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportesButton.setText("Reportes");
        ReportesButton.setBorder(null);
        ReportesButton.setBorderPainted(false);
        ReportesButton.setContentAreaFilled(false);
        ReportesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReportesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesButtonActionPerformed(evt);
            }
        });

        ClientesButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        ClientesButton.setForeground(new java.awt.Color(255, 255, 255));
        ClientesButton.setText("Clientes");
        ClientesButton.setBorder(null);
        ClientesButton.setBorderPainted(false);
        ClientesButton.setContentAreaFilled(false);
        ClientesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesButtonActionPerformed(evt);
            }
        });

        SalirButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        SalirButton.setForeground(new java.awt.Color(255, 255, 255));
        SalirButton.setText("Salir");
        SalirButton.setBorder(null);
        SalirButton.setBorderPainted(false);
        SalirButton.setContentAreaFilled(false);
        SalirButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        VentasButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        VentasButton.setForeground(new java.awt.Color(255, 255, 255));
        VentasButton.setText("Ventas");
        VentasButton.setBorder(null);
        VentasButton.setBorderPainted(false);
        VentasButton.setContentAreaFilled(false);
        VentasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasButtonActionPerformed(evt);
            }
        });

        GestionProductosButton.setBackground(new java.awt.Color(0, 67, 96));
        GestionProductosButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        GestionProductosButton.setForeground(new java.awt.Color(255, 255, 255));
        GestionProductosButton.setText("Gestion de Productos    ");
        GestionProductosButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GestionProductosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GestionProductosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionProductosButtonActionPerformed(evt);
            }
        });

        LogoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoSecciones.png"))); // NOI18N
        LogoButton.setBorder(null);
        LogoButton.setBorderPainted(false);
        LogoButton.setContentAreaFilled(false);
        LogoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNavegacionLayout = new javax.swing.GroupLayout(PanelNavegacion);
        PanelNavegacion.setLayout(PanelNavegacionLayout);
        PanelNavegacionLayout.setHorizontalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGroup(PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNavegacionLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VentasButton)
                            .addComponent(ReportesButton)
                            .addComponent(ClientesButton)
                            .addComponent(SalirButton)))
                    .addGroup(PanelNavegacionLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(GestionProductosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelNavegacionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(LogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        PanelNavegacionLayout.setVerticalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(LogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(GestionProductosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(VentasButton)
                .addGap(47, 47, 47)
                .addComponent(ReportesButton)
                .addGap(47, 47, 47)
                .addComponent(ClientesButton)
                .addGap(117, 117, 117)
                .addComponent(SalirButton))
        );

        getContentPane().add(PanelNavegacion);
        PanelNavegacion.setBounds(0, 0, 340, 900);

        PanelProductosCRUD.setBackground(new java.awt.Color(255, 239, 232));

        PrecioProductoGestion.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        PrecioProductoGestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        PrecioProductoGestion.setPreferredSize(new java.awt.Dimension(74, 25));

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel18.setText("FechaCreación:");

        FechaCreadoGestion.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        FechaCreadoGestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        FechaCreadoGestion.setPreferredSize(new java.awt.Dimension(74, 25));
        FechaCreadoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaCreadoGestionActionPerformed(evt);
            }
        });

        CodProductoGestion.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        CodProductoGestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        CodProductoGestion.setMinimumSize(new java.awt.Dimension(64, 25));
        CodProductoGestion.setPreferredSize(new java.awt.Dimension(74, 25));
        CodProductoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodProductoGestionActionPerformed(evt);
            }
        });

        StockProductoGestion.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        StockProductoGestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        StockProductoGestion.setPreferredSize(new java.awt.Dimension(74, 25));

        DescripcionProductoGestion.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        DescripcionProductoGestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        DescripcionProductoGestion.setPreferredSize(new java.awt.Dimension(74, 25));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel12.setText("Descripción:");

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel13.setText("CodProducto:");

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel14.setText("Buscar:");

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel15.setText("Productos");

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel16.setText("Stock:");

        BuscarProductoGestion.setBackground(new java.awt.Color(0, 118, 168));
        BuscarProductoGestion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BuscarProductoGestion.setForeground(new java.awt.Color(255, 255, 255));
        BuscarProductoGestion.setText("Buscar");
        BuscarProductoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProductoGestionActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel19.setText("FechaActualizado:");

        FechaModificadoGestion.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        FechaModificadoGestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        FechaModificadoGestion.setPreferredSize(new java.awt.Dimension(74, 25));

        BuscadorTextGestion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BuscadorTextGestion.setText("     ");
        BuscadorTextGestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        BuscadorTextGestion.setPreferredSize(new java.awt.Dimension(380, 27));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel17.setText("Precio:");

        ActualizarProductoGestion.setBackground(new java.awt.Color(210, 143, 0));
        ActualizarProductoGestion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        ActualizarProductoGestion.setForeground(new java.awt.Color(255, 255, 255));
        ActualizarProductoGestion.setText("Actualizar");
        ActualizarProductoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProductoGestionActionPerformed(evt);
            }
        });

        GuardarProductoGestion.setBackground(new java.awt.Color(0, 153, 0));
        GuardarProductoGestion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        GuardarProductoGestion.setForeground(new java.awt.Color(255, 255, 255));
        GuardarProductoGestion.setText("Guardar");
        GuardarProductoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarProductoGestionActionPerformed(evt);
            }
        });

        EliminarProductoGestion.setBackground(new java.awt.Color(204, 0, 0));
        EliminarProductoGestion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        EliminarProductoGestion.setForeground(new java.awt.Color(255, 255, 255));
        EliminarProductoGestion.setText("Eliminar");
        EliminarProductoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoGestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelProductosCRUDLayout = new javax.swing.GroupLayout(PanelProductosCRUD);
        PanelProductosCRUD.setLayout(PanelProductosCRUDLayout);
        PanelProductosCRUDLayout.setHorizontalGroup(
            PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                        .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13))
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DescripcionProductoGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CodProductoGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrecioProductoGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FechaModificadoGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StockProductoGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FechaCreadoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ActualizarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(BuscadorTextGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(124, 124, Short.MAX_VALUE))
        );
        PanelProductosCRUDLayout.setVerticalGroup(
            PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                        .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(FechaModificadoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscadorTextGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                        .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelProductosCRUDLayout.createSequentialGroup()
                                .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                                        .addComponent(CodProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DescripcionProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(GuardarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelProductosCRUDLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(BuscarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelProductosCRUDLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(PrecioProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(StockProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelProductosCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FechaCreadoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ActualizarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(EliminarProductoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );

        getContentPane().add(PanelProductosCRUD);
        PanelProductosCRUD.setBounds(340, 0, 700, 390);

        PanImageGestion.setBackground(new java.awt.Color(255, 239, 232));

        ImagenProducto.setBackground(new java.awt.Color(255, 255, 255));
        ImagenProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        BtnSubirImagen.setBackground(new java.awt.Color(0, 118, 168));
        BtnSubirImagen.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtnSubirImagen.setForeground(new java.awt.Color(255, 255, 255));
        BtnSubirImagen.setText("Subir Imagen");
        BtnSubirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubirImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanImageGestionLayout = new javax.swing.GroupLayout(PanImageGestion);
        PanImageGestion.setLayout(PanImageGestionLayout);
        PanImageGestionLayout.setHorizontalGroup(
            PanImageGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanImageGestionLayout.createSequentialGroup()
                .addGroup(PanImageGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanImageGestionLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(ImagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanImageGestionLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(BtnSubirImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        PanImageGestionLayout.setVerticalGroup(
            PanImageGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanImageGestionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ImagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSubirImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanImageGestion);
        PanImageGestion.setBounds(1040, 0, 400, 390);

        PanelProductos.setBackground(new java.awt.Color(255, 239, 232));
        PanelProductos.setLayout(null);

        TablaProductosGestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TablaProductosGestion);

        PanelProductos.add(jScrollPane3);
        jScrollPane3.setBounds(20, 20, 1050, 450);

        getContentPane().add(PanelProductos);
        PanelProductos.setBounds(340, 381, 1100, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReportesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesButtonActionPerformed
        Reportes reportes = new Reportes();  // Crear instancia del formulario
        reportes.setVisible(true);                           // Mostrar el formulario
        this.dispose();                                // Cerrar el formulario actual
    }//GEN-LAST:event_ReportesButtonActionPerformed

    private void ClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesButtonActionPerformed
        Clientes clientes = new Clientes();  // Crear instancia del formulario
        clientes.setVisible(true);                           // Mostrar el formulario
        this.dispose();                                // Cerrar el formulario actual
    }//GEN-LAST:event_ClientesButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        Login login = new Login();this.dispose();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void VentasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasButtonActionPerformed
        Ventas ventas= new Ventas();
        ventas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VentasButtonActionPerformed

    private void FechaCreadoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaCreadoGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaCreadoGestionActionPerformed

    private void CodProductoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodProductoGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodProductoGestionActionPerformed

    private void BuscarProductoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProductoGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarProductoGestionActionPerformed

    private void ActualizarProductoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProductoGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarProductoGestionActionPerformed

    private void GuardarProductoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarProductoGestionActionPerformed
        // 1) Leer textos de los campos
        String cod = CodProductoGestion.getText().trim();
        String descripcion = DescripcionProductoGestion.getText().trim();
        BigDecimal precio = new BigDecimal(PrecioProductoGestion.getText().trim());
        int stock = Integer.parseInt(StockProductoGestion.getText().trim());
        String rutaImagen = "- prueba -"; // Prueba
        
        // Obtiene usuario actual
        String codUsuario = SesionActual.getUsuarioActual().codUsuario();
        
        // Inserción de dato, fechaCrea, fechaModif no se llenan.
        ProductoDAO p = new ProductoDAOImpl();
        ProductoDTO pdto = new ProductoDTO(cod, descripcion, precio, stock, rutaImagen, codUsuario, null, null);
        try {
            p.guardar(pdto);
        } catch (DAOException ex) {
            System.out.println("");
        }

        // Limpiamos campos
        CodProductoGestion.setText("");
        DescripcionProductoGestion.setText("");
        PrecioProductoGestion.setText("");
        StockProductoGestion.setText("");
//----

    }//GEN-LAST:event_GuardarProductoGestionActionPerformed

    private void EliminarProductoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarProductoGestionActionPerformed

    private void BtnSubirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubirImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSubirImagenActionPerformed

    private void GestionProductosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionProductosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GestionProductosButtonActionPerformed

    private void LogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoButtonActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard = new Dashboard();  // Crear instancia del formulario
        dashboard.setVisible(true);                           // Mostrar el formulario
        this.dispose();
    }//GEN-LAST:event_LogoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionProductos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarProductoGestion;
    private javax.swing.JButton BtnSubirImagen;
    private javax.swing.JTextField BuscadorTextGestion;
    private javax.swing.JButton BuscarProductoGestion;
    private javax.swing.JButton ClientesButton;
    private javax.swing.JTextField CodProductoGestion;
    private javax.swing.JTextField DescripcionProductoGestion;
    private javax.swing.JButton EliminarProductoGestion;
    private javax.swing.JTextField FechaCreadoGestion;
    private javax.swing.JTextField FechaModificadoGestion;
    private javax.swing.JButton GestionProductosButton;
    private javax.swing.JButton GuardarProductoGestion;
    private javax.swing.JLabel ImagenProducto;
    private javax.swing.JButton LogoButton;
    private javax.swing.JPanel PanImageGestion;
    private javax.swing.JPanel PanelNavegacion;
    private javax.swing.JPanel PanelProductos;
    private javax.swing.JPanel PanelProductosCRUD;
    private javax.swing.JTextField PrecioProductoGestion;
    private javax.swing.JButton ReportesButton;
    private javax.swing.JButton SalirButton;
    private javax.swing.JTextField StockProductoGestion;
    private javax.swing.JTable TablaProductosGestion;
    private javax.swing.JButton VentasButton;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
