/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecsup.proyectofinal.view;

/**
 *
 * @author bob_s
 */
import com.tecsup.proyectofinal.controller.ReportesController;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class Reportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reportes.class.getName());
    private ReportesController controlador;


    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        setLocationRelativeTo(null); // centra la ventana en la pantalla
        this.controlador = new ReportesController(this);

    }

 
        // --- MÉTODOS PÚBLICOS PARA EL CONTROLADOR ---
    
    /**
     * Obtiene el texto del campo de búsqueda de factura.
     * @return El código de la factura a buscar.
     */
    public String getCodigoFacturaBuscada() {
        return BuscarFacturaReporte.getText();
    }
    
    /**
     * Devuelve el botón de búsqueda para que el controlador le añada un listener.
     * @return El objeto JButton de búsqueda.
     */
    public JButton getBuscarFacturaButton() {
        return BtBuscarFactura;
    }

    /**
     * Devuelve la tabla de detalles para que el controlador la pueda llenar.
     * @return El objeto JTable de la factura.
     */
    public JTable getTablaFactura() {
        return TablaFacturaReporte;
    }

        // --- NUEVO: Getters para los nuevos componentes ---
    public JButton getVentasDiaButton() { return BtVentasDia; }
    public JButton getVentasMesButton() { return BtVentasMes; }
    public JButton getStockMinimoButton() { return BtStockMinimo; }
    public JButton getProductosMasVendidosButton() { return BtProductosBest; }
    public JTable getTablaReportes2() { return Tabla2Reportes; }
    
    
    // --- Setters para que el controlador actualice la vista ---
    public void setNumFactura(String texto) { NumFacturaReportes.setText(texto); }
    public void setFechaVenta(String texto) { FechVentaReportes.setText(texto); }
    public void setNombreCliente(String texto) { NomClienteReportes.setText(texto); }
    public void setApellidoCliente(String texto) { ApClienteReportes.setText(texto); }
    public void setIgv(String texto) { igvReportes.setText(texto); }
    public void setTotal(String texto) { TotalReportes.setText(texto); }
    
    /**
     * Limpia todos los campos del formulario y la tabla de detalles.
     */
    public void limpiarCampos() {
        BuscarFacturaReporte.setText("");
        NumFacturaReportes.setText("");
        FechVentaReportes.setText("");
        NomClienteReportes.setText("");
        ApClienteReportes.setText("");
        igvReportes.setText("");
        TotalReportes.setText("");
        ((DefaultTableModel) TablaFacturaReporte.getModel()).setRowCount(0);
    }

    /**
     * Muestra un diálogo de mensaje genérico.
     * @param mensaje El texto a mostrar.
     * @param titulo El título de la ventana.
     * @param tipo El tipo de mensaje (de JOptionPane).
     */
    public void mostrarMensaje(String mensaje, String titulo, int tipo) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, tipo);
    }
    
    
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBuscarFactura7 = new javax.swing.JPanel();
        TotalReportes = new javax.swing.JTextField();
        BuscarFacturaReporte = new javax.swing.JTextField();
        igvReportes = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        BtBuscarFactura = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        TablaFacturaReporte = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        NumFacturaReportes = new javax.swing.JTextField();
        FechVentaReportes = new javax.swing.JTextField();
        NomClienteReportes = new javax.swing.JTextField();
        ApClienteReportes = new javax.swing.JTextField();
        PanelReportes2 = new javax.swing.JPanel();
        BtStockMinimo = new javax.swing.JButton();
        BtVentasDia = new javax.swing.JButton();
        BtProductosBest = new javax.swing.JButton();
        BtVentasMes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla2Reportes = new javax.swing.JTable();
        PanelNavegacion = new javax.swing.JPanel();
        GestionProductosButton = new javax.swing.JButton();
        ClientesButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        VentasButton = new javax.swing.JButton();
        ReportesButton = new javax.swing.JButton();
        LogoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 900));
        getContentPane().setLayout(null);

        PanelBuscarFactura7.setBackground(new java.awt.Color(255, 239, 232));

        TotalReportes.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        TotalReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        TotalReportes.setPreferredSize(new java.awt.Dimension(74, 25));

        BuscarFacturaReporte.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        BuscarFacturaReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        BuscarFacturaReporte.setMinimumSize(new java.awt.Dimension(64, 25));
        BuscarFacturaReporte.setPreferredSize(new java.awt.Dimension(74, 25));
        BuscarFacturaReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarFacturaReporteActionPerformed(evt);
            }
        });

        igvReportes.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        igvReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        igvReportes.setPreferredSize(new java.awt.Dimension(74, 25));

        jLabel75.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel75.setText("IGV (18%):");

        jLabel76.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel76.setText("Ingresar Número de Factura");

        jLabel77.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel77.setText("Facturas");

        jLabel78.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel78.setText("TOTAL:");

        BtBuscarFactura.setBackground(new java.awt.Color(0, 118, 168));
        BtBuscarFactura.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtBuscarFactura.setForeground(new java.awt.Color(255, 255, 255));
        BtBuscarFactura.setText("Buscar");
        BtBuscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarFacturaActionPerformed(evt);
            }
        });

        TablaFacturaReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Producto", "Cantidad", "PrecioVenta", "SubTotal"
            }
        ));
        jScrollPane9.setViewportView(TablaFacturaReporte);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel79.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel79.setText("Fecha de Venta:");

        jLabel80.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel80.setText("Cliente");

        jLabel81.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel81.setText("Factura Nº: ");

        jLabel82.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel82.setText("Apellido:");

        jLabel83.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel83.setText("Nombre:");

        NumFacturaReportes.setBackground(new java.awt.Color(204, 255, 255));
        NumFacturaReportes.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        NumFacturaReportes.setBorder(null);
        NumFacturaReportes.setPreferredSize(new java.awt.Dimension(74, 25));

        FechVentaReportes.setBackground(new java.awt.Color(204, 255, 255));
        FechVentaReportes.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        FechVentaReportes.setBorder(null);
        FechVentaReportes.setPreferredSize(new java.awt.Dimension(74, 25));

        NomClienteReportes.setBackground(new java.awt.Color(204, 255, 255));
        NomClienteReportes.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        NomClienteReportes.setBorder(null);
        NomClienteReportes.setPreferredSize(new java.awt.Dimension(74, 25));

        ApClienteReportes.setBackground(new java.awt.Color(204, 255, 255));
        ApClienteReportes.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        ApClienteReportes.setBorder(null);
        ApClienteReportes.setPreferredSize(new java.awt.Dimension(74, 25));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel80)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel83)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomClienteReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel81)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumFacturaReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel82)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApClienteReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel79)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FechVentaReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumFacturaReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechVentaReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApClienteReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomClienteReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout PanelBuscarFactura7Layout = new javax.swing.GroupLayout(PanelBuscarFactura7);
        PanelBuscarFactura7.setLayout(PanelBuscarFactura7Layout);
        PanelBuscarFactura7Layout.setHorizontalGroup(
            PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarFactura7Layout.createSequentialGroup()
                .addGap(216, 222, Short.MAX_VALUE)
                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel75)
                    .addComponent(jLabel78))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igvReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(BtBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                                .addComponent(jLabel76)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BuscarFacturaReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel77)))
                    .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBuscarFactura7Layout.setVerticalGroup(
            PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarFactura7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarFacturaReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(igvReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBuscarFactura7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        getContentPane().add(PanelBuscarFactura7);
        PanelBuscarFactura7.setBounds(340, 0, 520, 900);

        PanelReportes2.setBackground(new java.awt.Color(255, 239, 232));

        BtStockMinimo.setBackground(new java.awt.Color(204, 0, 0));
        BtStockMinimo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtStockMinimo.setForeground(new java.awt.Color(255, 255, 255));
        BtStockMinimo.setText("Productos por Agotarse");
        BtStockMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtStockMinimoActionPerformed(evt);
            }
        });

        BtVentasDia.setBackground(new java.awt.Color(0, 118, 168));
        BtVentasDia.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtVentasDia.setForeground(new java.awt.Color(255, 255, 255));
        BtVentasDia.setText("Ventas del Dia");
        BtVentasDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVentasDiaActionPerformed(evt);
            }
        });

        BtProductosBest.setBackground(new java.awt.Color(102, 153, 0));
        BtProductosBest.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtProductosBest.setForeground(new java.awt.Color(255, 255, 255));
        BtProductosBest.setText("Productos mas Vendidos");
        BtProductosBest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtProductosBestActionPerformed(evt);
            }
        });

        BtVentasMes.setBackground(new java.awt.Color(0, 118, 168));
        BtVentasMes.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtVentasMes.setForeground(new java.awt.Color(255, 255, 255));
        BtVentasMes.setText("Ventas del Mes");
        BtVentasMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVentasMesActionPerformed(evt);
            }
        });

        Tabla2Reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tabla2Reportes);

        javax.swing.GroupLayout PanelReportes2Layout = new javax.swing.GroupLayout(PanelReportes2);
        PanelReportes2.setLayout(PanelReportes2Layout);
        PanelReportes2Layout.setHorizontalGroup(
            PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReportes2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtVentasDia, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelReportes2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(BtProductosBest)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(PanelReportes2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(BtVentasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(PanelReportes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelReportes2Layout.setVerticalGroup(
            PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReportes2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtVentasDia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtVentasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelReportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtProductosBest, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        getContentPane().add(PanelReportes2);
        PanelReportes2.setBounds(860, 0, 580, 900);

        PanelNavegacion.setBackground(new java.awt.Color(0, 118, 168));
        PanelNavegacion.setPreferredSize(new java.awt.Dimension(339, 900));

        GestionProductosButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        GestionProductosButton.setForeground(new java.awt.Color(255, 255, 255));
        GestionProductosButton.setText("Gestion de Productos");
        GestionProductosButton.setBorder(null);
        GestionProductosButton.setBorderPainted(false);
        GestionProductosButton.setContentAreaFilled(false);
        GestionProductosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GestionProductosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionProductosButtonActionPerformed(evt);
            }
        });

        ClientesButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        ClientesButton.setForeground(new java.awt.Color(255, 255, 255));
        ClientesButton.setText("Clientes");
        ClientesButton.setBorder(null);
        ClientesButton.setBorderPainted(false);
        ClientesButton.setContentAreaFilled(false);
        ClientesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesButtonActionPerformed(evt);
            }
        });

        SalirButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        SalirButton.setForeground(new java.awt.Color(255, 255, 255));
        SalirButton.setText("Salir");
        SalirButton.setBorder(null);
        SalirButton.setBorderPainted(false);
        SalirButton.setContentAreaFilled(false);
        SalirButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        VentasButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        VentasButton.setForeground(new java.awt.Color(255, 255, 255));
        VentasButton.setText("Ventas");
        VentasButton.setBorder(null);
        VentasButton.setBorderPainted(false);
        VentasButton.setContentAreaFilled(false);
        VentasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasButtonActionPerformed(evt);
            }
        });

        ReportesButton.setBackground(new java.awt.Color(0, 67, 96));
        ReportesButton.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        ReportesButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportesButton.setText("Reportes                            ");
        ReportesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ReportesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReportesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesButtonActionPerformed(evt);
            }
        });

        LogoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoSecciones.png"))); // NOI18N
        LogoButton.setBorder(null);
        LogoButton.setBorderPainted(false);
        LogoButton.setContentAreaFilled(false);
        LogoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNavegacionLayout = new javax.swing.GroupLayout(PanelNavegacion);
        PanelNavegacion.setLayout(PanelNavegacionLayout);
        PanelNavegacionLayout.setHorizontalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGroup(PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNavegacionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ReportesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelNavegacionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GestionProductosButton)
                                .addComponent(VentasButton)
                                .addComponent(ClientesButton)
                                .addComponent(SalirButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNavegacionLayout.setVerticalGroup(
            PanelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavegacionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(LogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(GestionProductosButton)
                .addGap(47, 47, 47)
                .addComponent(VentasButton)
                .addGap(41, 41, 41)
                .addComponent(ReportesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(ClientesButton)
                .addGap(117, 117, 117)
                .addComponent(SalirButton))
        );

        getContentPane().add(PanelNavegacion);
        PanelNavegacion.setBounds(0, 0, 340, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionProductosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionProductosButtonActionPerformed
        GestionProductos gp = new GestionProductos();  // Crear instancia del formulario
        gp.setVisible(true);                           // Mostrar el formulario
        this.dispose();                                // Cerrar el formulario actual
    }//GEN-LAST:event_GestionProductosButtonActionPerformed

    private void ClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesButtonActionPerformed
        Clientes clientes = new Clientes();  // Crear instancia del formulario
        clientes.setVisible(true);                           // Mostrar el formulario
        this.dispose();                                // Cerrar el formulario actual
    }//GEN-LAST:event_ClientesButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        Login login = new Login();this.dispose();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void VentasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasButtonActionPerformed
        Ventas ventas= new Ventas();
        ventas.setVisible(true);
        this.dispose();    }//GEN-LAST:event_VentasButtonActionPerformed

    private void ReportesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportesButtonActionPerformed

    private void BtVentasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVentasMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtVentasMesActionPerformed

    private void BtProductosBestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtProductosBestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtProductosBestActionPerformed

    private void BtVentasDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVentasDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtVentasDiaActionPerformed

    private void BtStockMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtStockMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtStockMinimoActionPerformed

    private void BtBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtBuscarFacturaActionPerformed

    private void BuscarFacturaReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarFacturaReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarFacturaReporteActionPerformed

    private void LogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoButtonActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard = new Dashboard();  // Crear instancia del formulario
        dashboard.setVisible(true);                           // Mostrar el formulario
        this.dispose();
    }//GEN-LAST:event_LogoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApClienteReportes;
    private javax.swing.JButton BtBuscarFactura;
    private javax.swing.JButton BtProductosBest;
    private javax.swing.JButton BtStockMinimo;
    private javax.swing.JButton BtVentasDia;
    private javax.swing.JButton BtVentasMes;
    private javax.swing.JTextField BuscarFacturaReporte;
    private javax.swing.JButton ClientesButton;
    private javax.swing.JTextField FechVentaReportes;
    private javax.swing.JButton GestionProductosButton;
    private javax.swing.JButton LogoButton;
    private javax.swing.JTextField NomClienteReportes;
    private javax.swing.JTextField NumFacturaReportes;
    private javax.swing.JPanel PanelBuscarFactura7;
    private javax.swing.JPanel PanelNavegacion;
    private javax.swing.JPanel PanelReportes2;
    private javax.swing.JButton ReportesButton;
    private javax.swing.JButton SalirButton;
    private javax.swing.JTable Tabla2Reportes;
    private javax.swing.JTable TablaFacturaReporte;
    private javax.swing.JTextField TotalReportes;
    private javax.swing.JButton VentasButton;
    private javax.swing.JTextField igvReportes;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
